PREFIX aqp: <http://www.airqualitypredictor.org/ontology#>


SELECT ?control_station
            WHERE{
                ?control_station a aqp_classes:Suburban .
            }
            LIMIT 10


SELECT ?sub ?max_value ?day
            WHERE{
                ?sub a aqp_classes:PM10 .
                ?sub aqp_properties:hasMaxValue ?max_value .
                ?sub aqp_properties:atDay ?day .
                FILTER(?day = 1)
            }
            ORDER BY DESC(?max_value) LIMIT 10


SELECT DISTINCT ?prop
            WHERE{
                ?sub a aqp_classes:PM10 .
                ?sub ?prop ?value .
            }
